### ISSUE TITLE
Home screen lags when a lot of games have been played

### ISSUE THREAD

**Issue by alcalyn** [acristescu/OnlineGo#43]
Sometimes my screen freeze a little when I am on home page and a game is moving. All last played games boxes are also moving, and sometimes freezes my screen.

Maybe it should be paged / paginated (not sure how to write it)

**Comment by acristescu** [comment]
Hi @alcalyn can you please specify about how many active games you have at the same time and what phone are you using? I've never had any problems...

**Comment by popz73** [comment]
I also have this problem (I have 10 games running simultaneously at all
times). The home screen getting re-arranged with the updated game cards
freezes for about 1-3 seconds.

**Comment by alcalyn** [comment]
I would say more than 200, possibly 300. Freezes happens also when cards are rearranged i.e when a game finishes. I have only one or two simultaneously. My phone is a htc u play, released two years ago.

**Comment by acristescu** [comment]
Thank you for your replies. I will have to try to come up with a way to reproduce this issue before I can address it. Any suggestions on how I could get a surefire way of seing this would be appreciated.

**Comment by popz73** [comment]
hmm this stopped happening to me after installing the new release. 
On my case the slowness was probably from using a debug installation. Sorry!

**Comment by alcalyn** [comment]
Also me, it is because I see that all my games have disappeared except last 10 :p

**Comment by popz73** [comment]
Ah indeed didn't notice that. That should have "fixed" it yes :)

**Comment by acristescu** [comment]
Ah.... this is actually very useful, I think I understand what's going on... You see, what I'm doing is I'm fetching only the last 10 games from the server and the initial version of the app was only displaying those 10. At some point I introduced a database into the equation and I forgot to put the limit of 10 in there when fetching from it.

Basically I'm getting the last 10 games and storing and/or updating the games in the database. I then display ALL the games in the database. When you recently updated I nuked the local database (because I introduced modifications to the table structure to accomodate for the new notification system and it's easier to just nuke it instead of writing SQL migrations). That means you only have the last 10 games you finished in the database right now, but that will change as you finish more.

The solution would be to impleement proper pagination or re-introduce a limit of last 10 games.

**Comment by alcalyn** [comment]
Yes, I had only 10 games, but as soon I finished new games, I have more games.
I think that something like pagination or scroll load should prevent to always display hundreds of games

**Comment by acristescu** [comment]
Fixed as we now have a limit of how many games we display as expanded

**Comment by popz73** [comment]
I still have this issue after the last releases - I always have ~20 games
ongoing, and the screen freezes for 2-5 seconds when the game list is
reshuffled due to new moves

**Comment by acristescu** [comment]
Interesting... let's keep it open there, maybe I can find a way to reproduce and investigate...

**Comment by acristescu** [comment]
FYI this opened pandora's box... there are about 5 bugs that all contribute to the poor performance you've been experiencing. I never saw this because:

- I have a flagship phone (with me working on Android for a living I can justify having the good stuff). This hides performance issues behind a powerful processor...
- I never play more than 3-4 games at the same time
- I never realized the problem people are complaining was "when the game list is
reshuffled". When I looked at that particular moment I started seeing issues...

Anyway, I'm actually making progress fixing some of these issues but I may leave some open and see if the optimisation is enough...

**Comment by acristescu** [comment]
@popz73 this morning's version has a lot of optimisations for this. Please let me know if you see any improvement.

**Comment by popz73** [comment]
OMG

**Comment by popz73** [comment]
it's so much faster, I got so used to the jaggeddness that now it even feels _too fast_ :)
Seems definitely solved, well done

**Comment by popz73** [comment]
some related feedback: now the app takes much longer to load (when re-opening/switching back it after it's cycled out of memory), even if no new moves are played/ cards are moved.
It's still better than before as there's no longer any slowness when actively using the app, but reporting it still as I am not sure it is an intentional tradeoff

**Comment by acristescu** [comment]
It is indeed expected that the initial load time will take slightly longer. How long does it take for you and how many active games do you have?

**Comment by popz73** [comment]
now it takes 2-3seconds to load, while previously it was about half a second. 29 ongoing games + a few finished ones

**Comment by acristescu** [comment]
I'm afraid it will have to do for now...
